name: flutter_webview_app
description: A new Flutter project for FirstFinance.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons (iOS-style)
  cupertino_icons: ^1.0.8

  # ğŸŒ WebView & Permissions

  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1

  # ğŸ”¥ Firebase & Notifications
  firebase_core: ^2.25.0
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^17.0.0
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
